title: Data Cities
email: mail@uwethuemmel.com
description: >- 
 Collection of ressources around using data in cities. 
baseurl: ""
url: "https://datacities.github.io"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Collections
collections:
  strategies:
    output: true

# GitHub Repository
repository: datacities/datacities.github.io

# Navigation settings
navigation:
  - main

destination: _site


# Defaults for layouts to avoid missing layout errors
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "single"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_strategies"
    values:
      layout: "strategy"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
